name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test-job:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Check file exists
        run: |
          if [ -f hello.txt ]; then
            echo "Test passed: File exists."
          else
            echo "Test failed: File does not exist."
            exit 1
          fi
