name: Test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Validate file exists
        run: |
          if [ -f hello.txt ]; then
            echo "✅ File exists"
          else
            echo "❌ File does not exist"
            exit 1
          fi
