name: Test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: self-hosted

    steps:
      - name: Download build status artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml           # or "Deploy" if you used name:
          workflow_conclusion: success
          branch: main
          name: build-status
          path: .

      - name: Check if deployment was successful
        id: check
        run: |
          if grep -q "build successful" status.txt; then
            echo "✅ Build confirmed"
          else
            echo "❌ Build was not successful"
            exit 1
          fi
    
      - name: Download artifact from latest successful Build workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml            # or "Build" if you used 'name:' in build.yml
          workflow_conclusion: success
          branch: main                   # optional but recommended
          name: my-artifact              # must match what you uploaded
          path: .                        # where to extract (current dir)

      - name: Validate file exists
        run: |
          if [ -f hello.txt ]; then
            echo "✅ File exists"
          else
            echo "❌ File does not exist"
            exit 1
          fi
